#!/bin/bash
# Este script recibe un argumento y determina si es archivo o directorio.

if test  $# -lt 1 
then
error
elif test -d $1
then
echo "$1  es un directorio "
ls -l |du -h $1
elif test -f $1
then 
echo "$1  es un archivo"
else
echo "$1 no existe"
fi
